import os
import re
from tty import CC
import certifi
import airportsdata
import pycountry
from dotenv import load_dotenv

load_dotenv()

os .environ["SSL_CERT_FILE"] = certifi.where()
os.environ["REQUESTS_CA_BUNDLE"] = certifi.where()

API_KEY = os.getenv("AVIATIONSTACK_API_KEY")
DEFAULT_ORIGIN_IATA = os.getenv("DEFAULT_ORIGIN_IATA" , "DAC")
BASE_URL = "http://api.aviationstack.com/v1/flights"
AIRPORTS = airportsdata.load("IATA")

COUNTRY_ALISAS = {
    "Afghanistan" :	"AF" ,
    "afghanistan" : "AFG" , 
    "afghanistan" : "004" ,
    "albania" : "AL" ,
    "albania" : "ALB" ,
    "albania" : "008" ,
    "algeria" : "DZ" ,
    "algeria" : "DZA" ,
    "algeria" : "012" ,
    "american samoa" : "AS" ,
    "american samoa" : "ASM" ,
    "american samoa" : "016" ,
    "andorra" : "AD" ,
    "andorra" : "AND" ,
    "andorra" : "020" ,
    "angola" : "AO" ,
    "angola" : "AGO" ,
    "angola" : "024" ,
    "anguilla" : "AI" ,
    "anguilla" : "AIA" ,
    "anguilla" : "660" ,
    "antarctica" : "AQ" ,
    "antarctica" : "ATA" ,
    "antarctica" : "010" ,
    "antigua and barbuda" : "AG" ,
    "antigua and barbuda" : "ATG" ,
    "antigua and barbuda" : "028" ,
    "argentina" : "AR" ,
    "argentina" : "ARG" ,
    "argentina" : "032" ,
    "armenia" : "AM" ,
    "armenia" : "ARM" ,
    "armenia" : "051" ,
    "aruba" : "AW" ,
    "aruba" : "ABW" ,
    "aruba" : "533" ,
    "australia" : "AU" ,
    "australia" : "AUS" ,
    "australia" : "036" ,
    "austria" : "AT" ,
    "austria" : "AUT" ,
    "austria" : "040" ,
    "azerbaijan" : "AZ" ,
    "azerbaijan" : "AZE" ,
    "azerbaijan" : "031" ,
    "bahamas (the)" : "BS" ,
    "bahamas (the)" : "BHS" ,
    "bahamas (the)" : "044" ,
    "bonaire, sint eustatius and saba" : "BQ" ,
    "bonaire, sint eustatius and saba" : "BES" ,
    "bonaire, sint eustatius and saba" : "535" ,
    "bosnia and herzegovina" : "BA" ,
    "bosnia and herzegovina" : "BIH" ,
    "bosnia and herzegovina" : "070" ,
    "botswana" : "BW" ,
    "botswana" : "BWA" ,
    "botswana" : "072" ,
    "bouvet island" : "BV" ,
    "bouvet island" : "BVT" ,
    "bouvet island" : "074" ,
    "brazil" : "BR" ,
    "brazil" : "BRA" ,
    "brazil" : "076" ,
    "british indian ocean territory (the)" : "IO" ,
    "british indian ocean territory (the)" : "IOT" ,
    "british indian ocean territory (the)" : "086" ,
    "brunei darussalam" : "BN" ,
    "brunei darussalam" : "BRN" ,
    "brunei darussalam" : "096" ,
    "bulgaria" : "BG" ,
    "bulgaria" : "BGR" ,
    "bulgaria" : "100" ,
    "burkina faso" : "BF" ,
    "burkina faso" : "BFA" ,
    "burkina faso" : "854" ,
    "burundi" : "BI" ,
    "burundi" : "BDI" ,
    "burundi" : "108" ,    
    "Cocos (Keeling) Islands (the)"	: "CC",	
    "Cocos (Keeling) Islands (the)"	: "CCK",	
    "Cocos (Keeling) Islands (the)"	: "166",
    "colombia" : "CO" ,
    "colombia" : "COL" ,
    "colombia" : "170" ,
    "comoros (the)" : "KM" ,
    "comoros (the)" : "COM" ,
    "comoros (the)" : "174" ,
    "congo (the democratic republic of the)" : "CD" ,
    "congo (the democratic republic of the)" : "COD" ,
    "congo (the democratic republic of the)" : "180" ,
    "congo (the)" : "CG" ,
    "congo (the)" : "COG" ,
    "congo (the)" : "178" ,
    "cook islands (the)" : "CK" ,
    "cook islands (the)" : "COK" ,
    "cook islands (the)" : "184" ,
    "costa rica" : "CR" ,
    "costa rica" : "CRI" ,
    "costa rica" : "188" ,
    "croatia" : "HR" ,
    "croatia" : "HRV" ,
    "croatia" : "191" ,
    "cuba" : "CU" ,
    "cuba" : "CUB" ,
    "cuba" : "192" ,
    "curaçao" : "CW" ,
    "curaçao" : "CUW" ,
    "curaçao" : "531" ,
    "cyprus" : "CY" ,
    "cyprus" : "CYP" ,
    "cyprus" : "196" ,
    "czechia" : "CZ" ,
    "czechia" : "CZE" ,
    "czechia" : "203" ,
    "côte d'ivoire" : "CI" ,
    "côte d'ivoire" : "CIV" ,
    "côte d'ivoire" : "384" ,
    "ecuador" : "EC" ,
    "ecuador" : "ECU" ,
    "ecuador" : "218" ,
    "egypt" : "EG" ,
    "egypt" : "EGY" ,
    "egypt" : "818" ,
    "el salvador" : "SV" ,
    "el salvador" : "SLV" ,
    "el salvador" : "222" ,
    "equatorial guinea" : "GQ" ,
    "equatorial guinea" : "GNQ" ,
    "equatorial guinea" : "226" ,
    "eritrea" : "ER" ,
    "eritrea" : "ERI" ,
    "eritrea" : "232" ,
    "estonia" : "EE" ,
    "estonia" : "EST" ,
    "estonia" : "233" ,
    "eswatini" : "SZ" ,
    "eswatini" : "SWZ" ,
    "eswatini" : "748" ,
    "ethiopia" : "ET" ,
    "ethiopia" : "ETH" ,
    "ethiopia" : "231" ,
    "falkland islands (the) [malvinas]" : "FK" ,
    "falkland islands (the) [malvinas]" : "FLK" ,
    "falkland islands (the) [malvinas]" : "238" ,
    "faroe islands (the)" : "FO" ,
    "faroe islands (the)" : "FRO" ,
    "faroe islands (the)" : "234" ,
    "french southern territories (the)" : "TF" ,
    "french southern territories (the)" : "ATF" ,
    "french southern territories (the)" : "260" ,
    "gabon" : "GA" ,
    "gabon" : "GAB" ,
    "gabon" : "266" ,
    "gambia (the)" : "GM" ,
    "gambia (the)" : "GMB" ,
    "gambia (the)" : "270" ,
    "georgia" : "GE" ,
    "georgia" : "GEO" ,
    "georgia" : "268" ,
    "germany" : "DE" ,
    "germany" : "DEU" ,
    "germany" : "276" ,
    "ghana" : "GH" ,
    "ghana" : "GHA" ,
    "ghana" : "288" ,
    "gibraltar" : "GI" ,
    "gibraltar" : "GIB" ,
    "gibraltar" : "292" ,
    "greece" : "GR" ,
    "greece" : "GRC" ,
    "greece" : "300" ,
    "greenland" : "GL" ,
    "greenland" : "GRL" ,
    "greenland" : "304" ,
    "grenada" : "GD" ,
    "grenada" : "GRD" ,
    "grenada" : "308" ,
    "guadeloupe" : "GP" ,
    "guadeloupe" : "GLP" ,
    "guadeloupe" : "312" ,
    "guam" : "GU" ,
    "guam" : "GUM" ,
    "guam" : "316" ,
    "guatemala" : "GT" ,
    "guatemala" : "GTM" ,
    "guatemala" : "320" ,
    "guernsey" : "GG" ,
    "guernsey" : "GGY" ,
    "guernsey" : "831" ,
    "guinea" : "GN" ,
    "guinea" : "GIN" ,
    "guinea" : "324" , 
    "guinea-bissau" : "GW" ,
    "guinea-bissau" : "GNB" ,
    "guinea-bissau" : "624" ,
    "guyana" : "GY" ,
    "guyana" : "GUY" ,
    "guyana" : "328" ,
    "haiti" : "HT" ,
    "haiti" : "HTI" ,
    "haiti" : "332" ,
    "heard island and mcdonald islands" : "HM" ,
    "heard island and mcdonald islands" : "HMD" ,
    "heard island and mcdonald islands" : "334" ,
    "holy see (the)" : "VA" ,
    "holy see (the)" : "VAT" ,
    "holy see (the)" : "336" ,
    "honduras" : "HN" ,
    "honduras" : "HND" ,
    "honduras" : "340" ,
    "hong kong" : "HK" ,
    "hong kong" : "HKG" ,
    "hong kong" : "344" ,
    "hungary" : "HU" ,
    "hungary" : "HUN" ,
    "hungary" : "348" ,
    "indonesia" : "ID" ,
    "indonesia" : "IDN" ,
    "indonesia" : "360" ,
    "Iran (Islamic Republic of)" : "IR" ,
    "Iran (Islamic Republic of)" : "IRN" ,
    "Iran (Islamic Republic of)" : "364" ,
    "Iraq" : "IQ" ,
    "Iraq" : "IRQ" ,
    "Iraq" : "368" ,
    "Ireland" : "IE" ,
    "Ireland" : "IRL" ,
    "Ireland" : "372" ,
    "Isle of Man" : "IM" ,
    "Isle of Man" : "IMN" ,
    "Isle of Man" : "833" ,
    "Israel" : "IL" ,
    "Israel" : "ISR" ,
    "Israel" : "376" ,
    "Italy" : "IT" ,
    "Italy" : "ITA" ,
    "Italy" : "380" ,
    "Jamaica" : "JM" ,
    "Jamaica" : "JAM" ,
    "Jamaica" : "388" ,
    "Japan" : "JP" ,
    "Japan" : "JPN" ,
    "Japan" : "392" ,
    "Jersey" : "JE" ,
    "Jersey" : "JEY" ,
    "Jersey" : "832" ,
    "Jordan" : "JO" ,
    "Jordan" : "JOR" ,
    "Jordan" : "400" ,
    "kazakhstan" : "KZ" ,
    "kazakhstan" : "KAZ" ,
    "kazakhstan" : "398" ,
    "kenya" : "KE" ,
    "kenya" : "KEN" ,
    "kenya" : "404" ,
    "kiribati" : "KI" ,
    "kiribati" : "KIR" ,
    "kiribati" : "296" ,
    "korea (the democratic people's republic of)" : "KP" ,
    "korea (the democratic people's republic of)" : "PRK" ,
    "korea (the democratic people's republic of)" : "408" ,
    "korea (the republic of)" : "KR" ,
    "korea (the republic of)" : "KOR" ,
    "korea (the republic of)" : "410" ,
    "kuwait" : "KW" ,
    "kuwait" : "KWT" ,
    "kuwait" : "414" ,
    "kyrgyzstan" : "KG" ,
    "kyrgyzstan" : "KGZ" ,
    "kyrgyzstan" : "417" ,
    "lao people's democratic republic (the)" : "LA" ,
    "lao people's democratic republic (the)" : "LAO" ,
    "lao people's democratic republic (the)" : "418" ,
    "latvia" : "LV" ,
    "latvia" : "LVA" ,
    "latvia" : "428" ,
    "lebanon" : "LB" ,
    "lebanon" : "LBN" ,
    "lebanon" : "422" ,
    "lesotho" : "LS" ,
    "lesotho" : "LSO" ,
    "lesotho" : "426" ,
    "liberia" :"LR" ,
    "liberia" : "LBR" ,
    "liberia" :"430" ,
    "libya" : "LY" ,
    "libya" :"LBY" ,
    "libya" :"434" ,
    "liechtenstein" :"LI",
    "liechtenstein" :"LIE",
    "liechtenstein" :"438",
    "lithuania" :"LT",
    "lithuania" :"LTU",
    "lithuania" :"440",
    "Luxembourg" :"LU",
    "Luxembourg" :"LUX",
    "Luxembourg" :"442",
    "Macao" :"MO",
    "Macao" :"MAC",
    "Macao" :"446",
    "Madagascar" :"MG",
    "Madagascar" :"MDG",
    "Madagascar" :"450",
    "Malawi" :"MW",
    "Malawi" :"MWI",
    "Malawi" :"454",
    "Malaysia" :"MY",
    "Malaysia" :"MYS",
    "Malaysia" :"458",
    "Maldives" :"MV",
    "Maldives" :"MDV",
    "Maldives" :"462",
    "Mali" :"ML",
    "Mali" :"MLI",
    "Mali" :"466",
    "Malta" :"MT",
    "Malta" :"MLT",
    "Malta" :"470",
    "Marshall Islands (the)" :"MH",
    "Marshall Islands (the)" :"MHL",
    "Marshall Islands (the)" :"584",
    "Martinique" :"MQ",
    "Martinique" :"MTQ",
    "Martinique" :"474",
    "Mauritania" :"MR",
    "Mauritania" :"MRT",
    "Mauritania" :"478",
    "Mauritius" :"MU",
    "Mauritius" :"MUS",
    "Mauritius" :"480",
    "Mayotte" :"YT",
    "Mayotte" :"MYT",
    "Mayotte" :"175",
    "Mexico" :"MX",
    "Mexico" :"MEX",
    "Mexico" :"484",
    "Micronesia (Federated States of)" :"FM",
    "Micronesia (Federated States of)" :"FSM",
    "Micronesia (Federated States of)" :"583",
    "Moldova (the Republic of)" :"MD",
    "Moldova (the Republic of)" :"MDA",
    "Moldova (the Republic of)" :"498",
    "Monaco" :"MC",
    "Monaco" :"MCO",
    "Monaco" :"492",
    "Mongolia" :"MN",
    "Mongolia" :"MNG",
    "Mongolia" :"496",
    "Montenegro" :"ME",
    "Montenegro" :"MNE",
    "Montenegro" :"499",
    "Montserrat" :"MS",
    "Montserrat" :"MSR",
    "Montserrat" :"500",
    "Morocco" :"MA",
    "Morocco" :"MAR",
    "Morocco" :"504",
    "Mozambique" :"MZ",
    "Mozambique" :"MOZ",
    "Mozambique" :"508",
    "Myanmar" :"MM",
    "Myanmar" :"MMR",
    "Myanmar" :"104",
    "Namibia" :"NA",
    "Namibia" :"NAM",
    "Namibia" :"516",
    "Nauru" :"NR",
    "Nauru" :"NRU",
    "Nauru" :"520",
    "Nepal" :"NP",
    "Nepal" :"NPL",
    "Nepal" :"524",
    "Netherlands (the)" :"NL",
    "Netherlands (the)" :"NLD",
    "Netherlands (the)" :"528",
    "New Caledonia"	: "NC",
    "New Caledonia"	: "NCL",
    "New Caledonia"	: "540",
    "New Zealand" : "NZ",
    "New Zealand" : "NZL",
    "New Zealand" : "554",
    "Nicaragua" : "NI",
    "Nicaragua" : "NIC",
    "Nicaragua" : "558",
    "Niger (the)" : "NE",
    "Niger (the)" : "NER",
    "Niger (the)" : "562",
    "Nigeria" : "NG",
    "Nigeria" : "NGA",
    "Nigeria" : "566",
    "Niue" : "NU",
    "Niue" : "NIU",
    "Niue" : "570",
    "Norfolk Island" : "NF",
    "Norfolk Island" : "NFK",
    "Norfolk Island" : "574",
    "North Macedonia" : "MK",
    "North Macedonia" : "MKD",
    "North Macedonia" : "807",
    "Northern Mariana Islands (the)" : "MP",
    "Northern Mariana Islands (the)" : "MNP",
    "Northern Mariana Islands (the)" : "580",
    "Norway" : "NO",
    "Norway" : "NOR",
    "Norway" : "578",
    "Oman" : "OM",
    "Oman" : "OMN",
    "Oman" : "512",
    "Pakistan" : "PK",
    "Pakistan" : "PAK",
    "Pakistan" : "586",
    "Palau" : "PW",
    "Palau" : "PLW",
    "Palau" : "585",    
    "palestine, state of" : "PS",
    "palestine, state of" : "PSE",
    "palestine, state of" : "275",
    "Papua New Guinea"	: "PG",
    "Papua New Guinea"	: "PNG",
    "Papua New Guinea"	: "598",
    "Paraguay" : "PY",
    "Paraguay" : "PRY",
    "Paraguay" : "600",
    "Peru" : "PE",
    "Peru" : "PER",
    "Peru" : "604",
    "Philippines (the)" : "PH",
    "Philippines (the)" : "PHL",
    "Philippines (the)" : "608",
    "Pitcairn" : "PN",
    "Pitcairn" : "PCN",
    "Pitcairn" : "612",
    "Poland" : "PL",
    "Poland" : "POL",
    "Poland" : "616",
    "Portugal" : "PT",
    "Portugal" : "PRT",
    "Portugal" : "620",
    "Puerto Rico" : "PR",
    "Puerto Rico" : "PRI",
    "Puerto Rico" : "630",
    "Qatar" : "QA",
    "Qatar" : "QAT",
    "Qatar" : "634",
    "Romania" : "RO",
    "Romania" : "ROU",
    "Romania" : "642",
    "Russian Federation (the)" : "RU",
    "Russian Federation (the)" : "RUS",
    "Russian Federation (the)" : "643",
    "Rwanda" : "RW",
    "Rwanda" : "RWA",
    "Rwanda" : "646",
    "Réunion" : "RE",
    "Réunion" : "REU",
    "Réunion" : "638",
    "Saint Barthélemy" : "BL", 
    "Saint Barthélemy" : "BLM",
    "Saint Barthélemy" : "652",
    "Saint Kitts and Nevis" : "KN",
    "Saint Kitts and Nevis" : "KNA",
    "Saint Kitts and Nevis" : "659",
    "Saint Lucia" : "LC",
    "Saint Lucia" : "LCA",
    "Saint Lucia" : "662",
    "Saint Martin (French part)" : "MF",
    "Saint Martin (French part)" : "MAF",
    "Saint Martin (French part)" : "663",
    "Saint Pierre and Miquelon" : "PM",
    "Saint Pierre and Miquelon" : "SPM",
    "Saint Pierre and Miquelon" : "666",
    "Saint Vincent and the Grenadines" : "VC",
    "Saint Vincent and the Grenadines" : "VCT",
    "Saint Vincent and the Grenadines" : "670",
    "Samoa" : "WS",
    "Samoa" : "WSM",
    "Samoa" : "882",
    "Serbia" : "RS",
    "Serbia" : "SRB",
    "Serbia" : "688",
    "Seychelles" : "SC",
    "Seychelles" : "SYC",
    "Seychelles" : "690",
    "Sierra Leone" : "SL",
    "Sierra Leone" : "SLE",
    "Sierra Leone" : "694",
    "Singapore" : "SG",
    "Singapore" : "SGP",
    "Singapore" : "702" ,
    "Sint Maarten (Dutch part)" : "SX",
    "Sint Maarten (Dutch part)" : "SXM",
    "Sint Maarten (Dutch part)" : "534" ,
    "Slovakia" : "SK",
    "Slovakia" : "SVK",
    "Slovakia" : "703",
    "Slovenia" : "SI",
    "Slovenia" : "SVN",
    "Slovenia" : "705",
    "Solomon Islands" : "SB",
    "Solomon Islands" : "SLB",
    "Solomon Islands" : "090",
    "Somalia" : "SO",
    "Somalia" : "SOM",
    "Somalia" : "706",
    "South Africa" : "ZA",
    "South Africa" : "ZAF",
    "South Africa" : "710",
    "South Georgia and the South Sandwich Islands" : "GS",
    "South Georgia and the South Sandwich Islands" : "SGS",
    "South Georgia and the South Sandwich Islands" : "239",
    "South Sudan" : "SS",
    "South Sudan" : "SSD",
    "South Sudan" : "728",
    "Spain" : "ES",
    "Spain" : "ESP",
    "Spain" : "724",
    "Sri Lanka" : "LK",
    "Sri Lanka" : "LKA",
    "Sri Lanka" : "144",
    "Sudan (the)" : "SD",
    "Sudan (the)" : "SDN",
    "Sudan (the)" : "729",
    "Suriname" : "SR",
    "Suriname" : "SUR",
    "Suriname" : "740",
    "Svalbard and Jan Mayen" : "SJ",
    "Svalbard and Jan Mayen" : "SJM",
    "Svalbard and Jan Mayen" : "744",
    "Sweden" : "SE",
    "Sweden" : "SWE",
    "Sweden" : "752",
    "Switzerland" : "CH",
    "Switzerland" : "CHE",
    "Switzerland" : "756",
    "Syrian Arab Republic" : "SY",
    "Syrian Arab Republic" : "SYR",
    "Syrian Arab Republic" : "760",
    "Taiwan (Province of China)" : "TW",
    "Taiwan (Province of China)" :"TWN",
    "Taiwan (Province of China)" :"158",
    "Tajikistan" :"TJ",
    "Tajikistan" :"TJK",
    "Tajikistan" :"762",
    "Tanzania, United Republic of" :"TZ",
    "Tanzania, United Republic of" :"TZA",
    "Tanzania, United Republic of" :"834",
    "Thailand" :"THA",
    "Thailand" :"TH",
    "Thailand" :"764" ,
    "Timor-Leste" :"TL",
    "Timor-Leste" :"TLS",
    "Timor-Leste" :"626" ,
    "Togo" : "TG",
    "Togo" : "TGO",
    "Togo" : "768" ,
    "Tokelau" : "TK",
    "Tokelau" : "TKL",
    "Tokelau" : "772" ,
    "Tonga" : "TO",
    "Tonga" : "TON",
    "Tonga" : "776" ,
    "Trinidad and Tobago" : "TT",
    "Trinidad and Tobago" : "TTO",
    "Trinidad and Tobago" : "780" ,
    "Tunisia" : "TN",
    "Tunisia" : "TUN",
    "Tunisia" : "788" ,
    "Turkmenistan" : "TM",
    "Turkmenistan" : "TKM",
    "Turkmenistan" : "795" ,
    "Turks and Caicos Islands (the)" : "TC",
    "Turks and Caicos Islands (the)" : "TCA",
    "Turks and Caicos Islands (the)" : "796" ,
    "Tuvalu" : "TV",
    "Tuvalu" : "TUV",
    "Tuvalu" : "798" ,
    "Türkiye" : "TR",
    "Türkiye" : "TUR",
    "Türkiye" : "792" ,
    "Uganda" : "UG",
    "Uganda" : "UGA",
    "Uganda" : "800" ,
    "Ukraine" : "UA",
    "Ukraine" : "UKR",
    "Ukraine" : "804" ,
    "United Arab Emirates (the)" : "AE",
    "United Arab Emirates (the)" : "ARE",
    "United Arab Emirates (the)" : "784"    ,
    "United Kingdom of Great Britain and Northern Ireland (the)" : "GB",
    "United Kingdom of Great Britain and Northern Ireland (the)" : "GBR",
    "United Kingdom of Great Britain and Northern Ireland (the)" : "826" ,
    "United States Minor Outlying Islands (the)" : "UM",
    "United States Minor Outlying Islands (the)" : "UMI",
    "United States Minor Outlying Islands (the)" : "581" ,
    "United States of America (the)" : "US", 
    "United States of America (the)" : "USA",
    "United States of America (the)" : "840" ,
    "Uruguay" : "URY",
    "Uruguay" : "858" ,
    "Uzbekistan" : "UZ",
    "Uzbekistan" : "UZB",
    "Uzbekistan" : "860" ,
    "Vanuatu" : "VU",
    "Vanuatu" : "VUT",
    "Vanuatu" : "548" ,
    "Venezuela (Bolivarian Republic of)" : "VE",
    "Venezuela (Bolivarian Republic of)" : "VEN",
    "Venezuela (Bolivarian Republic of)" : "862" ,
    "Viet Nam" : "VN",
    "Viet Nam" : "VNM",
    "Viet Nam" : "704" ,
    "Virgin Islands (British)" : "VG",
    "Virgin Islands (British)" : "VGB",
    "Virgin Islands (British)" : "092" ,
    "Virgin Islands (U.S.)" : "VI",
    "Virgin Islands (U.S.)" : "VIR",
    "Virgin Islands (U.S.)" : "850" ,
    "Wallis and Futuna" : "WF",
    "Wallis and Futuna" : "WLF",
    "Wallis and Futuna" : "876" ,
    "Western Sahara" : "EH",
    "Western Sahara" : "ESH",
    "Western Sahara" : "732" ,
    "Yemen" : "YE",
    "Yemen" : "YEM",
    "Yemen" : "887" ,
    "Zambia" : "ZM",
    "Zambia" : "ZMB",
    "Zambia" : "894",
    "Zimbabwe" : "ZW",
    "Zimbabwe" : "ZWE",
    "Zimbabwe" : "716" ,
    "Åland Islands" : "AX",
    "Åland Islands" : "ALA",
    "Åland Islands" : "248"
}
